# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-29 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161026_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.CharField(default=datetime.datetime(2016, 10, 29, 6, 12, 3, 616424, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
