# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-15 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20161015_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('linkedin_oauth2', 'LinkedIn'), ('twitter', 'Twitter')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('linkedin_oauth2', 'LinkedIn'), ('twitter', 'Twitter')], max_length=30, verbose_name='provider'),
        ),
    ]
