# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-21 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20161015_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('linkedin_oauth2', 'LinkedIn'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('linkedin_oauth2', 'LinkedIn'), ('linkedin', 'LinkedIn'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=30, verbose_name='provider'),
        ),
    ]
