# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 12, 44, 43, 676232)),
        ),
    ]
