# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-13 12:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161013_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 12, 12, 46, 51, 159700)),
        ),
    ]
